spring.application.name=library-system

spring.datasource.url=jdbc:h2:file:./librarydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=library
spring.datasource.password=123456

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
